/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoucherRouteImport } from './routes/voucher'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses.index'
import { Route as DriversIndexRouteImport } from './routes/drivers.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as DriversDriverIdRouteImport } from './routes/drivers.$driverId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as TripsTripIdAuditRouteImport } from './routes/trips.$tripId.audit'
import { Route as ApiPublicBootstrapUserRouteImport } from './routes/api/public/bootstrap-user'

const VoucherRoute = VoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversDriverIdRoute = DriversDriverIdRouteImport.update({
  id: '/drivers/$driverId',
  path: '/drivers/$driverId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdAuditRoute = TripsTripIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => TripsTripIdRoute,
} as any)
const ApiPublicBootstrapUserRoute = ApiPublicBootstrapUserRouteImport.update({
  id: '/api/public/bootstrap-user',
  path: '/api/public/bootstrap-user',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/voucher': typeof VoucherRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/customers/': typeof CustomersIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/api/public/bootstrap-user': typeof ApiPublicBootstrapUserRoute
  '/trips/$tripId/audit': typeof TripsTripIdAuditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/voucher': typeof VoucherRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/customers': typeof CustomersIndexRoute
  '/drivers': typeof DriversIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/trips': typeof TripsIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/api/public/bootstrap-user': typeof ApiPublicBootstrapUserRoute
  '/trips/$tripId/audit': typeof TripsTripIdAuditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/voucher': typeof VoucherRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/trips/$tripId': typeof TripsTripIdRouteWithChildren
  '/customers/': typeof CustomersIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/api/public/bootstrap-user': typeof ApiPublicBootstrapUserRoute
  '/trips/$tripId/audit': typeof TripsTripIdAuditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/voucher'
    | '/customers/$customerId'
    | '/drivers/$driverId'
    | '/trips/$tripId'
    | '/customers/'
    | '/drivers/'
    | '/expenses/'
    | '/finance/'
    | '/settings/'
    | '/trips/'
    | '/vehicles/'
    | '/api/public/bootstrap-user'
    | '/trips/$tripId/audit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/voucher'
    | '/customers/$customerId'
    | '/drivers/$driverId'
    | '/trips/$tripId'
    | '/customers'
    | '/drivers'
    | '/expenses'
    | '/finance'
    | '/settings'
    | '/trips'
    | '/vehicles'
    | '/api/public/bootstrap-user'
    | '/trips/$tripId/audit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/voucher'
    | '/customers/$customerId'
    | '/drivers/$driverId'
    | '/trips/$tripId'
    | '/customers/'
    | '/drivers/'
    | '/expenses/'
    | '/finance/'
    | '/settings/'
    | '/trips/'
    | '/vehicles/'
    | '/api/public/bootstrap-user'
    | '/trips/$tripId/audit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  VoucherRoute: typeof VoucherRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  DriversDriverIdRoute: typeof DriversDriverIdRoute
  TripsTripIdRoute: typeof TripsTripIdRouteWithChildren
  CustomersIndexRoute: typeof CustomersIndexRoute
  DriversIndexRoute: typeof DriversIndexRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
  ApiPublicBootstrapUserRoute: typeof ApiPublicBootstrapUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voucher': {
      id: '/voucher'
      path: '/voucher'
      fullPath: '/voucher'
      preLoaderRoute: typeof VoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/$driverId': {
      id: '/drivers/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/drivers/$driverId'
      preLoaderRoute: typeof DriversDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId/audit': {
      id: '/trips/$tripId/audit'
      path: '/audit'
      fullPath: '/trips/$tripId/audit'
      preLoaderRoute: typeof TripsTripIdAuditRouteImport
      parentRoute: typeof TripsTripIdRoute
    }
    '/api/public/bootstrap-user': {
      id: '/api/public/bootstrap-user'
      path: '/api/public/bootstrap-user'
      fullPath: '/api/public/bootstrap-user'
      preLoaderRoute: typeof ApiPublicBootstrapUserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TripsTripIdRouteChildren {
  TripsTripIdAuditRoute: typeof TripsTripIdAuditRoute
}

const TripsTripIdRouteChildren: TripsTripIdRouteChildren = {
  TripsTripIdAuditRoute: TripsTripIdAuditRoute,
}

const TripsTripIdRouteWithChildren = TripsTripIdRoute._addFileChildren(
  TripsTripIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  VoucherRoute: VoucherRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  DriversDriverIdRoute: DriversDriverIdRoute,
  TripsTripIdRoute: TripsTripIdRouteWithChildren,
  CustomersIndexRoute: CustomersIndexRoute,
  DriversIndexRoute: DriversIndexRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
  ApiPublicBootstrapUserRoute: ApiPublicBootstrapUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
