/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoucherRouteImport } from './routes/voucher'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses.index'
import { Route as DriversIndexRouteImport } from './routes/drivers.index'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as DriversDriverIdRouteImport } from './routes/drivers.$driverId'

const VoucherRoute = VoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversDriverIdRoute = DriversDriverIdRouteImport.update({
  id: '/drivers/$driverId',
  path: '/drivers/$driverId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/voucher': typeof VoucherRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/drivers/': typeof DriversIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/voucher': typeof VoucherRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/drivers': typeof DriversIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/voucher': typeof VoucherRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/drivers/': typeof DriversIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/voucher'
    | '/drivers/$driverId'
    | '/trips/$tripId'
    | '/drivers/'
    | '/expenses/'
    | '/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/voucher'
    | '/drivers/$driverId'
    | '/trips/$tripId'
    | '/drivers'
    | '/expenses'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/voucher'
    | '/drivers/$driverId'
    | '/trips/$tripId'
    | '/drivers/'
    | '/expenses/'
    | '/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VoucherRoute: typeof VoucherRoute
  DriversDriverIdRoute: typeof DriversDriverIdRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  DriversIndexRoute: typeof DriversIndexRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voucher': {
      id: '/voucher'
      path: '/voucher'
      fullPath: '/voucher'
      preLoaderRoute: typeof VoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/$driverId': {
      id: '/drivers/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/drivers/$driverId'
      preLoaderRoute: typeof DriversDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VoucherRoute: VoucherRoute,
  DriversDriverIdRoute: DriversDriverIdRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  DriversIndexRoute: DriversIndexRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
